name: Workflow with multiple stage

on: push

jobs:
  job-on-ubuntu: #don't need to directly give name attribute here #job1
    runs-on: ubuntu-latest
    steps:
      -    run: date
      -    run: pwd
  job-on-windows: #job2
    name: A job running on windows
    runs-on: windows-latest
    steps:
      - name: First step in windows job #dash is for the steps
        run: date
      - run: ls
  dependent-job-1:
      needs: [job-on-ubuntu, job-on-windows]
      runs-on: macos-latest
      name: A job that runs on mac after the first two jobs
      steps:
       - run: pwd
       - name: new step
         run: ls
       - run: env
  dependent-job-2:
    needs: dependent-job-1
    runs-on: ubuntu-latest
    name: A final job
    steps:
      - run: echo Wow this is cooool!!
         
